/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface ImgLazy {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface ImgLazyAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'ImgLazy': Components.ImgLazy;
  }

  interface StencilIntrinsicElements {
    'img-lazy': Components.ImgLazyAttributes;
  }


  interface HTMLImgLazyElement extends Components.ImgLazy, HTMLStencilElement {}
  var HTMLImgLazyElement: {
    prototype: HTMLImgLazyElement;
    new (): HTMLImgLazyElement;
  };

  interface HTMLElementTagNameMap {
    'img-lazy': HTMLImgLazyElement
  }

  interface ElementTagNameMap {
    'img-lazy': HTMLImgLazyElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
